$('.music').slick({
    dots:true,
    slidesToShow:1,
    slidesToScroll:1,
});
$('.bg21').slick({
    arrows:true,
    slidesToShow:1,
    slidesToScroll:1,
    autoplay:true,
    autoplaySpeed:4000,
});